version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgres.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgres.conf"]

volumes:
  postgres_data: