version: "3.8"
services:
  ml_service:
    container_name: sabritonesMLContainer
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
